---
name: "🐞 Bug Report"
about: Report a bug or unexpected behavior
title: "[Bug] "
labels: type:bug
---

### Describe the bug
A clear and concise description of what the bug is.

### Steps to reproduce
1. Go to '...'
2. Run command '...'
3. See error

### Expected behavior
What you expected to happen instead.

### Environment
- Laravel version:
- PHP version:
- Package version:
